<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: artox-lab/exampleMessage/v1/order/created.proto

namespace GPBMetadata\ArtoxLab\ExampleMessage\V1\Order;

class Created
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
r
/artox-lab/exampleMessage/v1/order/created.proto ArtoxLab.ExampleMessage.V1.Order"
Created

id (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

